### ISSUE TITLE
This line will divide by zero if self.ratings is empty

### ISSUE THREAD

**Issue by karl-project-review** [sotanodroid/GB_PY_projects#3]
https://github.com/sotanodroid/GB_PY_projects/blob/21046c6386f31a949026cb7283469eba8dce8407/TomeRater.py#L72
If this method is called when self.ratings is empty, the script will throw an error and fail, since len(self.ratings) would be zero. Be sure to look for circumstances like this where your code might divide by zero depending on the input, and create a special case (ie an if statement that checks if self.ratings is empty) to deal with it.

**Comment by sotanodroid** [comment]
Thanks for pointed that, i've added ZeroDivisionError exception to avoid this
