### ISSUE TITLE
TomeRater Summary

### ISSUE THREAD

**Issue by karl-project-review** [sotanodroid/GB_PY_projects#4]
### Criteria 1: Valid Python Code
*_Score Level:_ 3/4 (Meets Expectations)
*_Comments:_ While your code passes the standard checks in the test file without any errors, there is a typo in line 61 and a potential division by zero in line 72 that will throw errors for more advanced checks. Make sure to test every piece of your code thoroughly to avoid having errors sneak by.

### Criteria 2: Implementation of Project Requirements
*_Score Level:_ 3/4 (Meets Expectations)
*_Comments:_ You implemented the vast majority of the requirements quite well. However, your add rating method should print an appropriate error message when an invalid rating is entered. Also, consider implementing one of the additional features mentioned near the end of the instructions, or a different feature that you think would improve TomeRater.

### Criteria 3: Software Architecture
*_Score Level:_ 4/4 (Exceeds Expectations)
*_Comments:_ You used classes and functions appropriately and avoided redundant code. Great work!

### Criteria 4: Uses Python Language Features
*_Score Level:_ 4/4 (Exceeds Expectations)
*_Comments:_ You used Python's language features everywhere it was appropriate. Good job!

### Overall Score: 14/16 (Meets Expectations)
Overall, this was a well-done project! You've demonstrated a solid understanding of classes, functions, and Python syntax, as well as an ability to break problems down into codable pieces. As a next step, I would encourage you to work on adding comments to your code, as clear comments are an important part of software development and will save you (or your coworkers) a lot of time when reading back through old files. Also, I'd encourage you to take the time to think about how to test this project more thoroughly. What additional test scripts could you have run to catch the errors I flagged? What else could you have tested? Again, great work!

**Comment by sotanodroid** [comment]
Many thanks for this review!

For me it was a pleasure to study this way, I am realy leveled up with python coding and now looking forward to build some new cool stuff.
